apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2021-07-19T07:18:24Z"
    generation: 1
    labels:
      app: demos
    name: demos
    namespace: default
    resourceVersion: "2065"
    selfLink: /apis/apps/v1/namespaces/default/deployments/demos
    uid: 1e4ff9bb-ad3d-45de-99b6-0feb096e6d39
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: demos
    
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: demos
      spec:
        containers:
        - image: app3p/node-task:0.0.2
          imagePullPolicy: IfNotPresent
          name: node-task
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2021-07-19T07:18:30Z"
      lastUpdateTime: "2021-07-19T07:18:30Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-07-19T07:18:24Z"
      lastUpdateTime: "2021-07-19T07:18:30Z"
      message: ReplicaSet "demos-695fd79cd9" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
