version: '3.7'
services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged:  true
        user: root
        ports: 
             - 8081:8000
             - 50000:50000
        container_name: jenkins
        volumes: 
          - /tmp/jenkins:/var/jenkins_home
